# Titanic - Machine Learning from Disaster


- Vamos utilizar os [dados disponíveis no Kaggle](https://www.kaggle.com/competitions/titanic)
    - É um dataset de **competição**
    - O resultado é avaliado através da **acurácia**:
        - _"Sua pontuação é a porcentagem de passageiros que você prevê corretamente. Isso é conhecido como acurácia."_

### Começando a entender a base

In [1]:
# Importando o pandas

import pandas as pd

In [2]:
# Visualizando a base de treino
treino= pd.read_csv(r"C:\Users\mike\Desktop\DADOS\PROJETOS\ML\PROJETO TITANIC\06-05 - Análise do Titanic - Projeto Completo\TITANIC\train.csv")

treino.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
# Criando o relatório

- **Agora vamos analisar essa base**

In [4]:
# Verificando as informações da base

treino.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
# Verificando o tipo dos dados

treino.dtypes.value_counts()

int64      5
object     5
float64    2
Name: count, dtype: int64

In [6]:
# E os valores nulos

treino.isnull().sum().sort_values(ascending=False)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
Pclass           0
Survived         0
Sex              0
Parch            0
SibSp            0
Fare             0
Ticket           0
dtype: int64

- **Agora vamos visualizar a base de teste**

In [7]:
# Visualizando a base de teste

teste = pd.read_csv(r"C:\Users\mike\Desktop\DADOS\PROJETOS\ML\PROJETO TITANIC\06-05 - Análise do Titanic - Projeto Completo\TITANIC\test.csv")
teste.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [8]:
# Verificando as informações da base

teste.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [9]:
# Analisando os valores nulos

teste.isnull().sum().sort_values(ascending=False)

Cabin          327
Age             86
Fare             1
Name             0
Pclass           0
PassengerId      0
Sex              0
Parch            0
SibSp            0
Ticket           0
Embarked         0
dtype: int64

- Temos colunas que **possuem valores vazios na base de teste que não estão vazias na base de treino** (nesse caso, precisaríamos tratar essas colunas apenas na base de teste)

### Realizando os tratamentos iniciais dos dados

- **Podemos começar tratando os valores vazios**

In [10]:
# Verificando novamente valores vazios para a base de treino

treino.isnull().sum().sort_values(ascending=False)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
Pclass           0
Survived         0
Sex              0
Parch            0
SibSp            0
Fare             0
Ticket           0
dtype: int64

In [11]:
# Retornando o shape da base

treino.shape

(891, 12)

In [12]:
# Visualizando novamente a base

treino.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
# Verificando a cardinalidade dos dados

treino.nunique().sort_values(ascending=False)

PassengerId    891
Name           891
Ticket         681
Fare           248
Cabin          147
Age             88
SibSp            7
Parch            7
Embarked         3
Pclass           3
Survived         2
Sex              2
dtype: int64

- Colunas com **alta cardinalidade** como nome, número do ticket e até mesmo o código da cabine não vão ajudar o modelo pois podem torná-lo **menos generalizável**. Nesse caso, vamos **eliminar essas colunas**

In [14]:
# Eliminando para a base de treino

treino = treino.drop(["Name", "Ticket", "Cabin"], axis=1)

In [15]:
# Também eliminando para a base de teste

teste = teste.drop(["Name", "Ticket", "Cabin"], axis=1)

- Agora precisamos tratar a coluna **Age**, que possui valores vazios tanto no treino quanto no teste
    - Como essa coluna possui a idade dos passageiros, podemos utilizar a **média das idades** para substituir os valores vazios

- Não podemos ter uma coluna de idade contendo dados vazios nesse caso, pode ser importante para nossa análise futura

In [16]:
# Verificando a média das idades para a base de treino
treino["Age"].mean()

np.float64(29.69911764705882)

In [17]:
teste["Age"].mean()

np.float64(30.272590361445783)

In [18]:
# Podemos agora selecionar as colunas com idade vazia e substituir por essa média

treino["Age"] = treino["Age"].fillna(treino["Age"].mean())

In [19]:
# E fazendo o mesmo para a base de teste

teste["Age"] = teste["Age"].fillna(teste["Age"].mean())

- Para a base de treino, ainda temos 2 valores vazios na coluna **Embarked**
    - Podemos verificar todos os valores nessa coluna e substituir os valores vazios pela **moda**

In [20]:
treino["Embarked"].isnull().sum()

np.int64(2)

In [21]:
# Verificando os valores na coluna Embarked

treino["Embarked"].value_counts()  #Vamos susbtituir os valores vazios presentes pela "moda" da coluna

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [22]:
# Selecionando a moda dessa coluna

treino["Embarked"].mode()[0]

'S'

In [23]:
# Substituindo os valores vazios

treino["Embarked"] = treino["Embarked"].fillna(treino["Embarked"].mode()[0])

- Para finalizar, para a base de teste ainda temos 1 valor vazio em **Fare**
    - Podemos utilizar a mesma lógica que fizemos para a coluna Age e substituir pela **moda**

In [24]:
teste["Fare"].isnull().sum()

np.int64(1)

In [25]:
# Verificando a média da coluna Fare para a base de teste

teste["Fare"].mean()

np.float64(35.627188489208635)

In [26]:
teste["Fare"] = teste["Fare"].fillna(teste["Fare"].mode()[0])

teste["Fare"].isnull().sum()  #verificamos que não temos mais ausência de dados nessa coluna

np.int64(0)

- **Verificando novamente os valores vazios**

In [27]:
# Para a base de treino

treino.isnull().sum().sort_values(ascending=False)

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [28]:
# Para a base de teste

teste.isnull().sum().sort_values(ascending=False)

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

### Considerando apenas as colunas que não são de texto

In [29]:
# Verificando as colunas de texto na base de treino

treino.columns[treino.dtypes !="object"]

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [30]:
# Selecionando apenas os valores numéricos da base de treino

treino_num = treino.select_dtypes(exclude="object")
treino_num.head()

   PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0            1         0       3  22.0      1      0   7.2500
1            2         1       1  38.0      1      0  71.2833
2            3         1       3  26.0      0      0   7.9250
3            4         1       1  35.0      1      0  53.1000
4            5         0       3  35.0      0      0   8.0500

In [31]:
# E para a base de teste

teste.columns[teste.dtypes !="object"]

Index(['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [32]:
# e os valores numéricos da base de teste

teste_num = teste.select_dtypes(exclude="object")
teste_num.head()

   PassengerId  Pclass   Age  SibSp  Parch     Fare
0          892       3  34.5      0      0   7.8292
1          893       3  47.0      1      0   7.0000
2          894       2  62.0      0      0   9.6875
3          895       3  27.0      0      0   8.6625
4          896       3  22.0      1      1  12.2875

### Podemos agora selecionar um modelo para classificar esses dados
- Para começar, vamos testar entre:
    - **Árvore de classificação**
        - https://scikit-learn.org/stable/modules/tree.html#classification
    - **Classificação dos vizinhos mais próximos**
        - https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier
    - **Regressão Logística**
        - https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression

- Antes de usar os algoritmos, precisamos separar a base de treino em **treino e validação**
    - Vamos fazer isso utilizando o **train_test_split**
        - https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

In [33]:
# Importando o train_test_split

from sklearn.model_selection import train_test_split

In [34]:
# Separando a base de treino em X e y

X = treino_num.drop(["PassengerId", "Survived"], axis=1)
y = treino["Survived"]

In [35]:
# Separando em treino e validação

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.33, random_state=42)

- Para a **árvore de classificação**

In [36]:
# Fazendo a importação

from sklearn import tree

In [37]:
# Criando o classificador

clf_ac = tree.DecisionTreeClassifier(random_state=42)  #"ac" se refere ao modelo árvore de classificação

In [38]:
# Fazendo o fit com os dados

clf_ac = clf_ac.fit(X_train, y_train)

In [39]:
# Fazendo a previsão

y_pred_ac = clf_ac.predict(X_val)

- Para o **KNeighborsClassifier**

In [40]:
# Importando

from sklearn.neighbors import KNeighborsClassifier

In [41]:
# Criando o classificador

clf_knn = KNeighborsClassifier(n_neighbors=2)

In [42]:
# Fazendo o fit com os dados

clf_knn = clf_knn.fit(X_train, y_train)

In [43]:
# Fazendo a previsão

y_pred_knn = clf_knn.predict(X_val)

- E para a **Regressão Logística**

In [44]:
# Importando

from sklearn.linear_model import LogisticRegression

In [45]:
# Criando o classificador

clf_rl = LogisticRegression(random_state=42)

In [46]:
# Fazendo o fit com os dados
clf_rl = clf_rl.fit(X_train, y_train)

In [47]:
# Fazendo a previsão
y_pred_rl = clf_rl.predict(X_val)

### E, para finalizar, vamos avaliar esses modelos
- Para fazer essa análise, podemos usar:
    - Acurácia (método de avaliação usado na competição):
        - https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html
    - Matriz de confusão (ajuda a visualizar a distribuição dos erros):
        - https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html

- Avaliando a **acurácia**

In [48]:
# Importando
from sklearn.metrics import accuracy_score

In [49]:
# Para a árvore
accuracy_score(y_val, y_pred_ac)

0.6169491525423729

In [50]:
# Para o knn
accuracy_score(y_val, y_pred_knn)

0.6237288135593221

In [51]:
# Para a regressão logística
accuracy_score(y_val, y_pred_rl)

0.7254237288135593

- Avaliando a **matriz de confusão**

In [52]:
# Importando
from sklearn.metrics import confusion_matrix

In [53]:
# Para a árvore
confusion_matrix(y_val, y_pred_ac)

array([[125,  50],
       [ 63,  57]])

In [54]:
# Para o knn
confusion_matrix(y_val, y_pred_knn)

array([[150,  25],
       [ 86,  34]])

In [55]:
# Para a regressão logística
confusion_matrix(y_val, y_pred_rl)

array([[156,  19],
       [ 62,  58]])

### Fazendo a previsão para os dados de teste
- Vamos usar o modelo com melhor precisão para fazer o predict na base de teste

In [56]:
# Visualizando o X_train
X_train.head()

     Pclass        Age  SibSp  Parch     Fare
6         1  54.000000      0      0  51.8625
718       3  29.699118      0      0  15.5000
685       2  25.000000      1      2  41.5792
73        3  26.000000      1      0  14.4542
882       3  22.000000      0      0  10.5167

In [57]:
# Visualizando a base de teste (apenas com valores numéricos)
teste_num.head()  #precisamos remover a coluna "passengerId" que não deveria estar aqui

   PassengerId  Pclass   Age  SibSp  Parch     Fare
0          892       3  34.5      0      0   7.8292
1          893       3  47.0      1      0   7.0000
2          894       2  62.0      0      0   9.6875
3          895       3  27.0      0      0   8.6625
4          896       3  22.0      1      1  12.2875

In [58]:
# Para a base de teste ser igual a base de treino, precisamos eliminar a coluna de id
X_test = teste_num.drop("PassengerId", axis=1)

In [59]:
# Utilizando a regressão logística na base de teste
y_pred_test = clf_rl.predict(X_test)

In [60]:
# Criando uma nova coluna com a previsão na base de teste
teste["Survived"] = y_pred_test

In [61]:
# Selecionando apenas a coluna de Id e Survived para fazer o envio
base_envio = teste[["PassengerId", "Survived"]]

In [62]:
# Exportando para um csv
base_envio.to_csv("resultado1.csv", index=False)